initialisation du css,dependence et back
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy pull request #1
Opened 2023-12-13 11:18 UTC by Sarhane64

2023-12-13 11:24 UTC, Defreitasnicolas approved these changes, later dismissed

2023-12-13 11:27 UTC, adelka69 approved these changes, later dismissed
nikel !

2023-12-13 13:38 UTC, jujuck requested changes
Ajout d'un fichier service de connexion avec axios

2023-12-13 13:38 UTC, jujuck commented on frontend/package.json
> +    "@emailjs/browser": "^3.11.0",
Pas de Email JS, on va faire l'envoie de mail par la backend sur ce projet avec Node Mailer

2023-12-13 13:38 UTC, jujuck commented on frontend/src/main.jsx
> +    ],
N'hésite pas à créer un layout admin avec une page dashboard...

2023-12-13 16:21 UTC, Defreitasnicolas submitted a review, later dismissed

2023-12-14 13:37 UTC, jujuck requested changes

2023-12-14 13:37 UTC, jujuck commented on frontend/connexion.js
> +  baseURL: "https://some-domain.com/api/",
Non, c'est import.meta.env.VITE_BACKEND_URL + /api et non pas same-domain.com

2023-12-14 13:37 UTC, jujuck commented on frontend/index.html
>      <title>Vite App</title>
Mettez tout de suite votre titre et votre favicon

2023-12-14 13:37 UTC, jujuck commented on frontend/src/main.jsx
> +        children: [{}],
Ajouter une page dans les children Admin

2023-12-14 13:37 UTC, jujuck commented on backend/seed.js
> +          "profile avatar",
Elle doit être unique

2023-12-14 14:38 UTC, Romeoseb-dev submitted a review, later dismissed

2023-12-14 14:44 UTC, jujuck requested changes

2023-12-14 14:44 UTC, jujuck commented on frontend/src/main.jsx
> +        path: "./admin",
Attention, Admin n'est pas un enfant de app, mais un élement à part entière

2023-12-14 14:54 UTC, Romeoseb-dev submitted a review, later dismissed

2023-12-14 14:55 UTC, jujuck commented on frontend/src/main.jsx
> +        path: "./admin",
le path n'est pas bon

2023-12-14 14:59 UTC, Romeoseb-dev submitted a review, later dismissed

2023-12-14 15:08 UTC, Romeoseb-dev approved these changes

2023-12-14 15:09 UTC, jujuck approved these changes

2023-12-14 15:10 UTC, merged