Inscription
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy pull request #13
Opened 2024-01-23 15:14 UTC by Defreitasnicolas

2024-01-23 16:20 UTC, Sarhane64 submitted a review, later dismissed

2024-01-24 08:19 UTC, jujuck requested changes, later dismissed

2024-01-24 08:19 UTC, jujuck commented on frontend/src/pages/auth/Signup.jsx
> +            type="text"
type= password

2024-01-24 10:19 UTC, aimach approved these changes

2024-01-24 10:20 UTC, Sarhane64 approved these changes

2024-01-24 10:20 UTC, merged