ajout du context + contextLogin + formulaire
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy pull request #20
Opened 2024-01-25 15:34 UTC by Sarhane64

2024-01-25 15:37 UTC, Defreitasnicolas submitted a review, later dismissed

2024-01-29 09:24 UTC, Defreitasnicolas approved these changes, later dismissed

2024-01-29 10:02 UTC, jujuck requested changes

2024-01-29 10:02 UTC, jujuck commented on backend/src/router.js
> +router.get("./login/:id", ProfilControllers.read);
mauvais nom de route

2024-01-29 10:02 UTC, jujuck commented on frontend/src/pages/auth/Login.jsx
> +      toast.success("Vous etes connecte");
Attention orthographe

2024-01-29 11:11 UTC, Defreitasnicolas approved these changes

2024-01-29 13:03 UTC, jujuck approved these changes

2024-01-29 13:03 UTC, merged