Comment
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy pull request #23
Opened 2024-01-30 15:17 UTC by Romeoseb-dev

2024-01-30 16:10 UTC, Defreitasnicolas approved these changes, later dismissed

2024-01-30 16:20 UTC, jujuck requested changes, later dismissed

2024-01-30 16:20 UTC, jujuck commented on frontend/src/components/Comment.jsx
> +      <p className="comment-number">nombre commentaires</p>
N en majuscule

2024-01-30 16:20 UTC, jujuck commented on frontend/src/components/Comment.jsx
> +        <p className="comment-link">Accéder au salon Tic-Tac-Toe</p>
Je pense qu'il n'y a pas besoin de p

2024-01-30 16:20 UTC, jujuck commented on frontend/src/pages/PageComment.jsx
> +    const fetchData = async () => {
Nomme la fonction getComments et on la place en dehors du useEffect

2024-01-30 16:20 UTC, jujuck commented on frontend/src/pages/PageComment.jsx
> +      const response = await connexion.get("/comments");
sur le coup, utilise getComments

2024-01-30 16:20 UTC, jujuck commented on frontend/src/pages/PageComment.jsx
> +              <input
ajoute une balise label avec un aria-label

2024-01-30 16:20 UTC, jujuck commented on backend/src/router.js
> +router.get("/comments/:id", commentControllers.read);
met la en commentaire

2024-01-30 16:20 UTC, jujuck commented on backend/src/models/CommentManager.js
> +  async read(id) {
En commentaire

2024-01-30 16:20 UTC, jujuck commented on backend/src/models/CommentManager.js
> +  async update(comment, id) {
En commentaire

2024-01-30 16:20 UTC, jujuck commented on backend/src/models/CommentManager.js
> +  async delete(id) {
En commentaire

2024-01-30 16:20 UTC, jujuck commented on backend/src/controllers/commentControllers.js
> +// Import access to database tables
Mets en commentaire les fonctions non utilisées

2024-02-02 16:01 UTC, aimach requested changes

2024-02-02 16:01 UTC, aimach commented on frontend/src/pages/PageComment.jsx
> +                label="comment"
ce n'est pas ça, il faut mettre une balise label autour de l'input 
https://developer.mozilla.org/fr/docs/Web/HTML/Element/label

2024-02-05 08:37 UTC, aimach submitted a review, later dismissed

2024-02-05 14:07 UTC, aimach submitted a review, later dismissed

2024-02-06 08:17 UTC, jujuck approved these changes, later dismissed

2024-02-06 08:21 UTC, merged