jeu tictactoe
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy pull request #3
Opened 2023-12-22 08:23 UTC by Romeoseb-dev

2023-12-22 08:26 UTC, Sarhane64 submitted a review, later dismissed

2023-12-22 09:37 UTC, aimach requested changes

2023-12-22 09:37 UTC, aimach commented on frontend/src/pages/TicTacToe.jsx
> +        <h1 className="game-tic">Tic Tac Toe</h1>
plutôt h2 ou h3

2023-12-22 09:37 UTC, aimach commented on frontend/src/style/index.scss
> +@import "./components/TicTacToe.scss";
pourquoi faire un import ici ?

2023-12-22 11:22 UTC, Defreitasnicolas submitted a review, later dismissed

2023-12-22 14:36 UTC, Romeoseb-dev commented on frontend/src/style/index.scss
> +@import "./components/TicTacToe.scss";
nous avons un dossier avec tout les imports scss au meme endroit, si on fait des imports dans le fichier jsx, ça nous mets des erreurs de linter

2023-12-22 14:52 UTC, jujuck requested changes

2023-12-22 14:52 UTC, jujuck commented on frontend/components/TicTacToeComponents/Board.jsx
> +
Pas de ligne morte

2023-12-22 14:52 UTC, jujuck commented on frontend/src/pages/Home.jsx
> +    <div>
Mettre des fragments <></> et non des <div>

2023-12-22 14:52 UTC, jujuck commented on frontend/src/pages/TicTacToe.jsx
> +  function handleClick(i) {
faire des functions fléchées const handleClick

2023-12-22 14:52 UTC, jujuck commented on frontend/src/pages/TicTacToe.jsx
> +  function handleRestart() {
Idem

2023-12-22 14:52 UTC, jujuck commented on frontend/src/pages/TicTacToe.jsx
> +  function handleComputerMove(squares) {
idem

2023-12-22 14:52 UTC, jujuck commented on frontend/src/pages/TicTacToe.jsx
> +      <div>{status}</div>
Mettre directement le ternaire du status

2024-01-03 09:31 UTC, Sarhane64 approved these changes

2024-01-03 09:43 UTC, jujuck approved these changes

2024-01-03 09:45 UTC, merged