Users admin page
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Wildy-Gamy pull request #4
Opened 2024-01-03 08:54 UTC by Defreitasnicolas

2024-01-03 08:59 UTC, Sarhane64 submitted a review, later dismissed

2024-01-03 09:29 UTC, jujuck submitted a review, later dismissed

2024-01-03 09:29 UTC, jujuck commented on backend/src/controllers/playerControllers.js
> +    res.json(players);
Manque le status(200)

2024-01-03 09:29 UTC, jujuck commented on backend/src/models/PlayerManager.js
> +    const [rows] = await this.database.query(`select * from ${this.table}`);
Pas de select *, on récupère que l'email et les autres infos... Mais pas le mot de passe

2024-01-03 09:29 UTC, jujuck commented on frontend/src/main.jsx
> +        loader: () => {
A mettre en useEffect avec un state dans ta page

2024-01-03 09:29 UTC, jujuck commented on frontend/src/pages/AdminUsersPage.jsx
> +
Mettre le useEffect et utiliser une query sur la requete pour filtrer
useEffect(() => {
  ...ta requete /api/players?username=${search}
}, [search])

2024-01-03 09:29 UTC, jujuck commented on frontend/src/pages/AdminUsersPage.jsx
> +          data={usersData}
Essaie de supprimer l'aspect data... le composant sera plus réutilisable

2024-01-03 09:29 UTC, jujuck commented on frontend/src/components/DeleteButton.jsx
> +    <div>
Est'ce que la div est utile

2024-01-03 09:29 UTC, jujuck commented on frontend/src/components/AdminUsersTable.jsx
> +    <div>
Est ce que la div est utile

2024-01-03 15:02 UTC, Sarhane64 approved these changes, later dismissed

2024-01-03 15:23 UTC, jujuck requested changes

2024-01-03 15:23 UTC, jujuck commented on frontend/src/components/InputSearchBar.jsx
> +        onChange={handleSearch}
Met directement (e) => setSearch(e.target.value)

2024-01-03 15:23 UTC, jujuck commented on frontend/src/components/AdminUsersTable.jsx
> +  const getUsers = async () => {
Mettre un saut de ligne

2024-01-03 15:23 UTC, jujuck commented on frontend/src/components/AdminUsersTable.jsx
> +  };
Mettre un saut de ligne

2024-01-03 15:34 UTC, Sarhane64 submitted a review, later dismissed

2024-01-04 13:59 UTC, jujuck requested changes

2024-01-04 13:59 UTC, jujuck commented on backend/src/models/PlayerManager.js
> +      `select id, username, email from ${this.table} where username LIKE "%${search}%"`
?
[`"%${search}%"`]

2024-01-04 14:29 UTC, Romeoseb-dev approved these changes

2024-01-04 15:04 UTC, jujuck approved these changes

2024-01-04 15:04 UTC, merged